name: soundanalyzer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - numpy
  - scipy
  - matplotlib
  - python-sounddevice
  - portaudio
  - ipykernel
  - pyaudio
  - pyqtgraph
  - PySide6